### ISSUE TITLE
ToDo for v4

### ISSUE THREAD

**Issue by vertesy** [vertesy/MarkdownReports#90]
### Current code

- [ ] Fix bugs
      - [ ] with `wstripchart` 
      - [ ] with `wvioplot` 
      - [ ] `md.image.linker` uses `b.usepng` and ignores the parent functions PNG variable

- [ ] More consistent naming
      - [ ] Choose between google and hadley style

### CRAN

- [ ] Build on win
- [ ] Read and apply CRAN docs
- [ ] 
- [ ] 

### Enhancement

- [x] Draw wflowcharts with `wflowchart()`
     - [x] Look into `irequireDiagrammeR)`
